var pictureList = [
    "../img/alabama.PNG",
    "../img/alaska.PNG",
    "../img/arizona.PNG",
    "../img/arkansas.PNG",
	"../img/california.PNG",
    "../img/colorado.PNG",
    "../img/Connecticut.PNG",
    "../img/Delaware.PNG",
	"../img/Florida.PNG",
    "../img/Georgia.PNG",
    "../img/Hawaii.PNG",
    "../img/Idaho.PNG",
	"../img/Illinois.PNG",
    "../img/Indiana.PNG",
    "../img/Iowa.PNG",
    "../img/Kansas.PNG",
	"../img/Kentucky.PNG",
    "../img/Louisiana.PNG",
	"../img/Massachusetts.PNG",
	"../img/Maryland.PNG",
	"../img/Maine.PNG",
	"../img/Michigan.PNG",
	"../img/Minnesota.PNG",
	"../img/Missouri.PNG",
	"../img/Mississippi.PNG",
	"../img/Montana.PNG",
	"../img/North Carolina.PNG",
	"../img/North Dakota.PNG",
	"../img/Nebraska.PNG",
	"../img/New Hampshire.PNG",
	"../img/New Jersey.PNG",
	"../img/New Mexico.PNG",
	"../img/Nevada.PNG",
	"../img/New York.PNG",
	"../img/Ohio.PNG",
	"../img/Oklahoma.PNG",
	"../img/Oregon.PNG",
	"../img/Pennsylvania.PNG",
	"../img/Rhode Island.PNG",
	"../img/South Carolina.PNG",
	"../img/South Dakota.PNG",
	"../img/Tennessee.PNG",
	"../img/Texas.PNG",
	"../img/Utah.PNG",
	"../img/Virginia.PNG",
	"../img/Vermont.PNG",
	"../img/Washington.PNG",
	"../img/Wisconsin.PNG",
	"../img/West Virginia.PNG",
	"../img/Wyoming.PNG", ];

var $sc = $('#state_area')

$('#picDD').change(function () {
	var val = $(this).val();
	$sc.children('img').attr("src", pictureList[val-1]);
})